#drowing plot4
> png("plot4.png")
> par(mfrow = c(2, 2))
> plot(hpc_s$DateTime, hpc_s$Global_active_power, type="l",xlab="", ylab="Global Active Power (in kilowatts)")
> plot(hpc_s$DateTime, hpc_s$Voltage, type="l",xlab="datetime", ylab="Voltage")
> plot(hpc_s$DateTime, hpc_s$Sub_metering_1, type="l",xlab="", ylab="Energy sub metering")
> points(hpc_s$DateTime, hpc_s$Sub_metering_2, type="l", col="red")
> points(hpc_s$DateTime, hpc_s$Sub_metering_3, type="l", col="blue")
> legend("topright", col=c("black","red","blue"), pch=c("___","___","___"),legend=c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
> plot(hpc_s$DateTime, hpc_s$Global_reactive_power, type="l",xlab="datetime", ylab="Global_reactive_power")
> dev.off()
